name: Feature request
description: As a user, I want to request a feature for aiges
title: "[Feature]: "
labels: [kind/feature]
assignees:
  - sea-wyq
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to request a feature for aiges! 
- type: textarea
  attributes:
    label: Tell us what feature you want?
    description: A concise description of the problem you are facing or the motivetion behind this feature request..
  validations:
    required: true
