name: Bug Report
description: As a user, I want to file a bug for aiges
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - sea-wyq
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Additional Information
      description: Please copy and paste any relevant Info output. 
      render: shell
